---
- name: "sudoers: Don't prompt for password"
  lineinfile:
     path: /etc/sudoers
     line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
     insertafter: EOF
     validate: '/usr/sbin/visudo -cf %s'

- name: "Gnome Theme: flat-remix"
  block:
    - name: "gnome-theme: ppa"
      apt_repository:
        repo: "ppa:daniruiz/flat-remix"
        validate_certs: no
      ignore_errors: yes
    - name: "gnome-theme: flat-remix"
      apt:
        name: "{{ item }}"
      loop:
        - flat-remix
        - flat-remix-gnome
        - flat-remix-gtk
        - imagemagick
        - libglib2.0-dev-bin

- name: "Gnome Themes: github"
  become: yes
  become_user: "{{ user }}"
  ignore_errors: yes
  tags: gnome, themes
  block:
    - file:
        path: "{{ item }}"
        state: directory
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0755
      loop:
        - '/home/{{ user }}/.themes'
        - '/home/{{ user }}/.icons'
    - name: "Gnome Themes: Nordic"
      git:
        repo: "https://github.com/EliverLara/Nordic.git"
        depth: 1
        dest: "/home/{{ user }}/.themes/Nordic"
    - name: "Gnome Themes: Nordic Polar"
      git:
        repo: "https://github.com/EliverLara/Nordic-Polar.git"
        dest: "/home/{{ user }}/.themes/Nordic-Polar"
        depth: 1
    - name: "Gnome Themes: Ant"
      git:
        repo: "https://github.com/EliverLara/Ant.git"
        dest: "/home/{{ user }}/.themes/Ant"
        depth: 1
    - name: "MacOS Themes"
      git:
        repo: "https://github.com/paullinuxthemer/Mc-OS-themes.git"
        dest: "/home/{{ user }}/.themes"
        depth: 1
    - name: "eOS-Sierra-Gtk"
      git:
        repo: "https://github.com/btd1337/eOS-Sierra-Gtk.git"
        dest: "/home/{{ user }}/.themes/eOs-Sierra-Gtk"
        depth: 1
    - name: "la-capitaine-icon-theme"
      git:
        repo: "https://github.com/keeferrourke/la-capitaine-icon-theme.git"
        dest: "/home/{{ user }}/.icons/la-capitaine-icon-theme"
        depth: 1

- name: Terminator with Nord theme
  block:
    - file:
        path: '/home/{{ user }}/.config/terminator'
        state: directory
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0755
    - stat:
        path: "/home/{{ user }}/.config/terminator/config"
      register: ansible_config
    - block:
      - git:
          repo: https://github.com/arcticicestudio/nord-terminator.git
          dest: /tmp/nord
          depth: 1
      - copy:
          src: '/tmp/nord/src/config'
          dest: '/home/{{ user }}/.config/terminator/config'
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: 0644
      - replace:
          dest: '/home/{{ user }}/.config/terminator/config'
          regexp: 'nord'
          replace: 'default'
      - lineinfile:
          dest: '/home/{{ user }}/.config/terminator/config'
          regexp: '^background_color'
          insertafter: '^background_color'
          line: "    {{ item.property }} = {{ item.value }}"
        with_items:
          - { property: 'background_darkness', value: '0.9' }
          - { property: 'background_type',     value: 'transparent' }
          - { property: 'scrollback_lines',    value: '50000' }
          - { property: 'font',                value: 'Liberation Mono 8' }
          - { property: 'use_system_font',     value: 'False' }
      when: not ansible_config.stat.exists

- name: Instala extensoes do VSCode
  tags: programming, vscode
  block:
  - name: "VSCode Extensions"
    ignore_errors: yes
    include_role:
      name: ansible-role-visual-studio-code-extensions
    vars:
      visual_studio_code_extensions_build: stable
      users:
        - username: "{{ user }}"
          visual_studio_code_extensions:
            - timonwong.ansible-autocomplete
            - dbaeumer.vscode-eslint
            - mauve.terraform
            - 4ops.terraform
            - donjayamanne.githistory
          visual_studio_code_extensions_absent:
            - seanmcbreen.Spell
