---
- hosts: localhost
  connection: local
  roles:
    - role: ansible-role-desktop-softwares
      become: yes
      vars:
        install:
          - anaconda
          - apt-packages
          # - bash-powerline-shell
          - google-chrome
          - docker-ce
          # - gimp
          - gnome-themes-github
          # - gnome-theme-flat-remix
          # - google-cloud-sdk
          - graphics-drivers
          - insomnia
          - keybase
          - mcos-bigsur
          - menlo-font
          - meslolgs-font # vscode terminal font
          - nerdfonts
          - obs-studio
          - paper-icon-theme
          - python3-packages
          # - R-base
          # - R-studio
          # - terminator
          - typora
          # - virtualbox
          - visual-studio-code
          - vscode-extensions
          - zafiro-icons

    - role: ansible-role-software-customizations
      become: yes
      vars:
        configure:
          - color-emoji
          # - gnome-keyring-credential-helper
          - remove-ubuntu-dock
          - sudoers
          # - terminator-nord-theme
          - timedatectl
          - tmp.mount
