---
- name: "Installing apt-keys"
  apt_key: 
    url: "{{ item }}" 
    state: present
  with_items:
    - "https://dl-ssl.google.com/linux/linux_signing_key.pub"

- name: "Installing Snaps"
  snap:
    name: "{{ item }}"
    state: present
    channel: latest/edge
  loop:
    - docker
    - vlc

- name: "Adding Google Chrome stable repository"
  lineinfile:
     path: /etc/apt/sources.list.d/google-chrome.list
     line: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
     create: yes

- name: Add PPAs
  apt_repository:
    repo: '{{ item }}'
    validate_certs: no
  with_items:
    - ppa:noobslab/icons
    - ppa:otto-kesselgulasch/gimp
    - ppa:graphics-drivers/ppa
    - ppa:daniruiz/flat-remix
  ignore_errors: yes

- name: Trusty PPAs
  apt_repository:
    repo: "{{ item }}"
    validate_certs: no
    codename: trusty
  loop:
    - ppa:gnome-terminator/nightly-gtk3
    - ppa:noobslab/themes 

- name: Upgrade packages
  apt:
    upgrade: yes
    dpkg_options: 'force-confold,force-confdef'
    autoremove: yes
    update_cache: yes
  ignore_errors: yes

- name: Remove unity look
  apt:
    state: absent
    name: gnome-shell-extension-ubuntu-dock

- name: Install Packages
  apt:
    name: "{{ item }}"
    state: latest
    dpkg_options: 'force-confdef,force-confold'
  loop: 
    - flat-remix
    - flat-remix-gnome
    - flat-remix-gtk
    - fonts-powerline
    - fonts-fantasque-sans
    - python3-pip
    - vim
    - git
    - gnome-tweak-tool
    - gnome-shell-extensions
    - gnome-themes-standard
    - google-chrome-stable
    - chrome-gnome-shell
    - gnome-shell-extensions
    - lm-sensors
    - gnome-shell-extension-weather
    - terminator
    - curl
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - ubuntu-make
    - gimp
    - network-manager-openvpn-gnome
    - deluge
    - htop
    - docker-ce
    - asciinema
    - httpie
    - expect
    - ubuntu-restricted-extras
  ignore_errors: yes

- name: Install Keybase
  apt:
    deb: "{{ item }}"
  with_items:
    - https://prerelease.keybase.io/keybase_amd64.deb

- name: Install powerline-shell
  pip:
    name: powerline-shell
    state: latest

- name: Install http-prompt
  pip:
    name: http-prompt
    state: latest

- name: "Add {{ user }} to docker group"
  user:
    name: "{{ user }}"
    groups: "docker"
    append: yes

- name: Habilita powerline-shell
  blockinfile:
    path: /etc/bash.bashrc
    insertafter: EOF
    content: |
      function _update_ps1() {
        PS1=$(powerline-shell $?)
      }
      if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
         PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
      fi

- name: Instala VSCode
  block:
    - name: "Verifica se VSCode já está instalado"
      tags: dev, vscode, visual-studio-code
      stat:
        path: "{{ visual_studio_code_path }}/code"
      register: vscode_installed
    - name: "Cria symlink para 'code'"
      tags: dev, vscode, visual-studio-code
      file:
        src: "{{ visual_studio_code_binary }}" 
        dest: "{{ visual_studio_code_path }}/code"
        owner: "{{ user }}"
        group: "{{ user }}"
        state: link
      when: vscode_installed.stat.exists == false
    - name: Instala VsCode
      tags: dev, vscode, visual-studio-code
      become_user: "{{ user }}"
      shell: "yes | umake ide visual-studio-code --accept-license {{ visual_studio_code_path }}"
      when: vscode_installed.stat.exists == false

- name: Instala fonte Menlo monospace
  block:
    - name: Clona repositorio
      git:
        repo: https://github.com/abertsch/Menlo-for-Powerline.git
        dest: /tmp/menlo
    - name: Copia fonte
      copy:
        src: "/tmp/menlo/Menlo for Powerline.ttf"
        dest: /usr/share/fonts
    - name: Atualiza cache de fontes
      shell:
        cmd: fc-cache -f -v
  ignore_errors: yes 
