galaxy_info:
  author: Fabio Rizzi
  description: Personal customizations
  company: None
  license: MIT
  min_ansible_version: 2.9
  galaxy_tags: []

dependencies:
  - src: https://github.com/gantsign/ansible-role-visual-studio-code-extensions
    when: '"ide" is defined and "ide" in install'
