galaxy_info:
  author: Fabio Rizzi
  description: Packages
  company: None
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 19.10
  galaxy_tags:
    - ubuntu
    - eoan
    - fabiodbr
    - desktop
dependencies: []
